//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoteCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dosages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dosages()
        {
            this.TreatmentDetails = new HashSet<TreatmentDetails>();
            this.PatientMedications = new HashSet<PatientMedications>();
        }
    
        public int DosageID { get; set; }
        public int MedicationID { get; set; }
        public string Dosage { get; set; }
        public string Frequency { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string RouteOfAdministration { get; set; }
        public string Instructions { get; set; }
        public string DosageAmount { get; set; }
        public Nullable<int> PatientID { get; set; }
    
        public virtual Medications Medications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentDetails> TreatmentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientMedications> PatientMedications { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
