//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoteCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dosage
    {
        public int DosageID { get; set; }
        public int MedicationID { get; set; }
        public string Dosage1 { get; set; }
        public string Frequency { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string RouteOfAdministration { get; set; }
        public string Instructions { get; set; }
    
        public virtual Medications Medication { get; set; }
    }
}
