//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoteCare.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PatientNurseAssignment
    {
        [Display(Name = "M‰‰r‰ys")]
        public int AssignmentID { get; set; }
        [Display(Name = "Potilas")]
        public int PatientID { get; set; }
        [Display(Name = "Hoitaja")]
        public int NurseID { get; set; }
        [Display(Name = "L‰‰k‰ri")]
        public Nullable<int> DoctorID { get; set; }
        [Display(Name = "M‰‰r‰ysp‰iv‰m‰‰r‰")]
        public System.DateTime AssignmentDate { get; set; }
    
        public virtual Doctors Doctors { get; set; }
        public virtual Nurses Nurses { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
