//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoteCare.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Patients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patients()
        {
            this.Diagnoses = new HashSet<Diagnoses>();
            this.PatientHistory = new HashSet<PatientHistory>();
            this.PatientMedications = new HashSet<PatientMedications>();
            this.VitalFunctions = new HashSet<VitalFunctions>();
            this.Treatment = new HashSet<Treatment>();
            this.Dosages = new HashSet<Dosages>();
        }


        [Display(Name = "Potilas ID")]
        public int PatientID { get; set; }

        [Display(Name = "Etunimi")]
        public string FirstName { get; set; }

        [Display(Name = "Sukunimi")]
        public string LastName { get; set; }

        [Display(Name = "Syntymäaika")]
        public System.DateTime DateOfBirth { get; set; }

        [Display(Name = "Sukupuoli")]
        public string Gender { get; set; }

        [Display(Name = "Osoite")]
        public string Address { get; set; }

        [Display(Name = "Puhelinnumero")]
        public string PhoneNumber { get; set; }

        [Display(Name = "Sähköposti")]
        public string Email { get; set; }

        [Display(Name = "Hätäyhteyshenkilö")]
        public string EmergencyContactName { get; set; }

        [Display(Name = "Hätäyhteyshenkilö puhelinnumero")]
        public string EmergencyContactPhone { get; set; }

        [Display(Name = "Hoitaja ID")]
        public Nullable<int> NurseID { get; set; }

        [Display(Name = "Lääkäri ID")]
        public Nullable<int> DoctorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnoses> Diagnoses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientHistory> PatientHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientMedications> PatientMedications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VitalFunctions> VitalFunctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Treatment> Treatment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dosages> Dosages { get; set; }
        public virtual Doctors Doctors { get; set; }
        public virtual Nurses Nurses { get; set; }
    }
}
