//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoteCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientHistory
    {
        public int HistoryID { get; set; }
        public int PatientID { get; set; }
        public string ConditionName { get; set; }
        public Nullable<System.DateTime> DiagnosisDate { get; set; }
        public string TreatmentDetails { get; set; }
        public Nullable<System.DateTime> SurgeryDate { get; set; }
        public string Notes { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
