//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoteCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientNurseAssignment
    {
        public int AssignmentID { get; set; }
        public int PatientID { get; set; }
        public int NurseID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public System.DateTime AssignmentDate { get; set; }
    
        public virtual Doctors Doctors { get; set; }
        public virtual Nurses Nurses { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
