//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoteCare.Models
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Migrations;

    public partial class PatientRecordDataEntities : DbContext
    {
        public PatientRecordDataEntities()
            : base("name=PatientRecordDataEntities")
        {
            Database.SetInitializer(new MigrateDatabaseToLatestVersion<PatientRecordDataEntities, Configuration>());
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Doctors> Doctors { get; set; }
        public virtual DbSet<Medications> Medications { get; set; }
        public virtual DbSet<Nurses> Nurses { get; set; }
        public virtual DbSet<PatientHistory> PatientHistory { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Treatment> Treatment { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<VitalFunctions> VitalFunctions { get; set; }
    }
    public class Configuration : DbMigrationsConfiguration<PatientRecordDataEntities>
    {
        public Configuration() 
        { 
            AutomaticMigrationsEnabled = true; //Tallentaa/päivittää automaattisesti tietokannan.
        }

        protected override void Seed(PatientRecordDataEntities context)
        {
            context.Medications.AddOrUpdate(
                m => m.MedicationName,
                new Medications { MedicationName = "Bisoprolol", Dosage = "2,5 mg", Frequency = "1x päivässä", RouteOfAdministration = "Suun kautta" },
                new Medications { MedicationName = "Nitrosid", Dosage = "5 mg", Frequency = "2x päivässä", RouteOfAdministration = "s.c" },
                new Medications { MedicationName = "Diformin retard", Dosage = "500 mg", Frequency = "3x päivässä", RouteOfAdministration = "Suun kautta" },
                new Medications { MedicationName = "Jardiance", Dosage = "5 mg", Frequency = "2x päivässä" , RouteOfAdministration = "Suun kautta" },
                new Medications { MedicationName = "Paratabs", Dosage = "500 mg", Frequency = "3x päivässä" , RouteOfAdministration = "Suun kautta" },
                new Medications { MedicationName = "Disperin", Dosage = "100 mg", Frequency = "1x päivässä" , RouteOfAdministration = "Suun kautta" },
                new Medications { MedicationName = "Essitalopram orion", Dosage = "5 mg", Frequency = "1x päivässä" , RouteOfAdministration = "Suun kautta" }
                );

            // Tähän voi lisätä lisää Seed dataa muille tauluille 

            context.SaveChanges();
        }
    }
}
