//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoteCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMedication
    {
        public int PatientMedicationID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> MedicationID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> MedicationListID { get; set; }
    
        public virtual MedicationList MedicationList { get; set; }
        public virtual Medications Medication { get; set; }
        public virtual Patients Patient { get; set; }
    }
}
