//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoteCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentDetails
    {
        public int TreatmentDetailID { get; set; }
        public int TreatmentID { get; set; }
        public int MedicationID { get; set; }
        public Nullable<int> DosageID { get; set; }
        public Nullable<int> DoctorID { get; set; }
    
        public virtual Doctors Doctors { get; set; }
        public virtual Dosages Dosages { get; set; }
        public virtual Medications Medications { get; set; }
        public virtual Treatment Treatment { get; set; }
    }
}
